apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-server
  labels:
    app: demo-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: demo-server
    spec:
      containers:
        - image: 428630729476.dkr.ecr.ap-south-1.amazonaws.com/server:v14
          imagePullPolicy: Always
          name: demo-server
          ports:
            - containerPort: 8080
              protocol: TCP
